### ISSUE TITLE
You are amazing but i want to ask something

### ISSUE THREAD

**Issue by alokm014** [karoldvl/EARS#11]
you are using too much thing and i want to detect voices and print on my console screen instead of local server.... is it possible to delete all files which is related with local server and make ur code simple...plz help me

**Comment by karolpiczak** [comment]
At this moment I have no plans/time to make major modifications to this project. I might revisit it when doing a larger rewrite at a later stage. At the moment you could try streamlining it by using the code from `audio.py` without the Bokeh cruft, most elements are already in place for a console app.
