### ISSUE TITLE
Questions - Logging and Trigger

### ISSUE THREAD

**Issue by umsaenga** [karoldvl/EARS#17]
Hello, this is a great idea.  Can I ask question please.

Does this keep log of when a sound was recognized and for how long?

Can you point me to best place to insert a trigger task for when a sound is recognized?

Thank you

**Comment by karolpiczak** [comment]
No, there's no such functionality. You could do something like this after: https://github.com/karolpiczak/EARS/blob/04bd36aea7cd27cc28b4757a0a25c997d1412ff7/ears/audio.py#L136.

**Comment by umsaenga** [comment]
thank you I will try.
