### ISSUE TITLE
About "python2 -m sounddevice" command

### ISSUE THREAD

**Issue by iamblue** [karoldvl/EARS#5]
I type this command in my mac, and show it:
```
> 0 Built-in Microphone, Core Audio (2 in, 0 out)
< 1 Built-in Output, Core Audio (0 in, 2 out)
```
 How could I name my microphone in `/ears/config.py` at line6 ? 
Thx~

**Comment by karoldvl** [comment]
According to the [docs](https://python-sounddevice.readthedocs.io/en/0.3.10/#sounddevice.default) either naming by substring (I think ```'Built-in'``` might apply here, not sure about that) or using specific device IDs for input/output (```0, 1```) should work:

```python
AUDIO_DEVICE = 0, 1
```

**Comment by iamblue** [comment]
OK ~~ thank you.
