### ISSUE TITLE
compiling EARS log - everything alright?

### ISSUE THREAD

**Issue by tmm2018** [karoldvl/EARS#8]
when running a modified version of EARS run script, on ubuntu x86_64, i get the following log.
my script says

bokeh serve --allow-websocket-origin=127.0.0.1:5006 ears

everything seems to run fine, but i cannot tell exactly if all the modules comiled successfully

here's my terminal log

./run.sh
INFO:bokeh.server.server:Starting Bokeh server version 0.12.5
DEBUG:bokeh.server.tornado:These host origins can connect to the websocket: ['127.0.0.1:5006']
DEBUG:bokeh.server.tornado:Patterns are:
DEBUG:bokeh.server.tornado:  [('/ears/?',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.doc_handler.DocHandler'>,
DEBUG:bokeh.server.tornado:    {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x7f2f091d35c0>,
DEBUG:bokeh.server.tornado:     'bokeh_websocket_path': '/ears/ws'}),
DEBUG:bokeh.server.tornado:   ('/ears/ws',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.ws.WSHandler'>,
DEBUG:bokeh.server.tornado:    {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x7f2f091d35c0>,
DEBUG:bokeh.server.tornado:     'bokeh_websocket_path': '/ears/ws'}),
DEBUG:bokeh.server.tornado:   ('/ears/autoload.js',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.autoload_js_handler.AutoloadJsHandler'>,
DEBUG:bokeh.server.tornado:    {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x7f2f091d35c0>,
DEBUG:bokeh.server.tornado:     'bokeh_websocket_path': '/ears/ws'}),
DEBUG:bokeh.server.tornado:   ('/ears/static/(.*)',
DEBUG:bokeh.server.tornado:    <class 'tornado.web.StaticFileHandler'>,
DEBUG:bokeh.server.tornado:    {'path': '/home/tmm88/Workspace/EARS/ears/static'}),
DEBUG:bokeh.server.tornado:   ('/?',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.root_handler.RootHandler'>,
DEBUG:bokeh.server.tornado:    {'applications': {'/ears': <bokeh.server.application_context.ApplicationContext object at 0x7f2f091d35c0>},
DEBUG:bokeh.server.tornado:     'prefix': '',
DEBUG:bokeh.server.tornado:     'use_redirect': True}),
DEBUG:bokeh.server.tornado:   ('/static/(.*)',
DEBUG:bokeh.server.tornado:    <class 'bokeh.server.views.static_handler.StaticHandler'>)]
INFO:bokeh.command.subcommands.serve:Starting Bokeh server on port 5006 with applications at paths ['/ears']
INFO:bokeh.command.subcommands.serve:Starting Bokeh server with process id: 9686
INFO:audio:Initializing a convolutional neural network model...
Using Theano backend.
WARNING:theano.tensor.blas:Using NumPy C-API based implementation for BLAS functions.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tmm88/Workspace/EARS/ears/audio.py", line 78, in start
    model.load_weights('ears/model.h5')
  File "/home/tmm88/.local/lib/python3.5/site-packages/keras/models.py", line 723, in load_weights
    raise ImportError('`load_weights` requires h5py.')
ImportError: `load_weights` requires h5py.

DEBUG:bokeh.server.tornado:[pid 9686] 0 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 0 sessions with 0 unused
DEBUG:bokeh.server.tornado:[pid 9686] 0 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 0 sessions with 0 unused
DEBUG:bokeh.server.tornado:[pid 9686] 0 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 0 sessions with 0 unused
DEBUG:bokeh.server.tornado:[pid 9686] 0 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 0 sessions with 0 unused
INFO:tornado.access:302 GET / (127.0.0.1) 7.26ms
INFO:tornado.access:200 GET /ears (127.0.0.1) 539.48ms
INFO:tornado.access:200 GET /ears/static/css/bootstrap.css (127.0.0.1) 90.55ms
INFO:tornado.access:200 GET /static/css/bokeh.min.css?v=1bb409ee97bc7539326089bbfc2aad84 (127.0.0.1) 0.98ms
INFO:tornado.access:200 GET /static/css/bokeh-widgets.min.css?v=de1aa4588db0ebb1076588c26ac1e07c (127.0.0.1) 1.09ms
INFO:tornado.access:200 GET /static/js/bokeh.min.js?v=d5277ec06271e90def555abd13cd3b2f (127.0.0.1) 1.75ms
INFO:tornado.access:200 GET /static/js/bokeh-widgets.min.js?v=ff67b7fa94bb9ebef0e0e2c97f8c95f0 (127.0.0.1) 1.39ms
INFO:tornado.access:200 GET /ears/static/css/custom.css (127.0.0.1) 56.15ms
INFO:tornado.access:200 GET /static/js/bokeh-gl.min.js?v=dac0ba7cb19b33bf935e67b96a95b546 (127.0.0.1) 1.90ms
INFO:tornado.access:200 GET /ears/static/js/bootstrap.min.js (127.0.0.1) 26.06ms
INFO:tornado.access:200 GET /ears/static/js/custom.js (127.0.0.1) 14.85ms
INFO:bokeh.server.views.ws:WebSocket connection opened
DEBUG:bokeh.server.views.ws:Receiver created for Protocol('1.0')
DEBUG:bokeh.server.views.ws:ServerHandler created for Protocol('1.0')
INFO:bokeh.server.views.ws:ServerConnection created
DEBUG:bokeh.server.session:Sending pull-doc-reply from session 'FaQmL9wUZBfOZU2Z10aUOTYcTbpyMBFdpnWaCKqMkkBi'
/home/tmm88/.local/lib/python3.5/site-packages/bokeh/core/json_encoder.py:73: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access Timestamp as pandas.Timestamp
  if pd and isinstance(obj, pd.tslib.Timestamp):
/home/tmm88/.local/lib/python3.5/site-packages/bokeh/core/json_encoder.py:75: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(type(obj), np.float):
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.68ms
DEBUG:bokeh.server.tornado:[pid 9686] 1 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 1 sessions with 0 unused
DEBUG:bokeh.server.tornado:[pid 9686] 1 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 1 sessions with 0 unused
DEBUG:bokeh.server.tornado:[pid 9686] 1 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 1 sessions with 0 unused
DEBUG:bokeh.server.tornado:[pid 9686] 1 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 1 sessions with 0 unused
DEBUG:bokeh.server.tornado:[pid 9686] 1 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 1 sessions with 0 unused
DEBUG:bokeh.server.tornado:[pid 9686] 1 clients connected
DEBUG:bokeh.server.tornado:[pid 9686]   /ears has 1 sessions with 0 unused
^C
Interrupted, shutting down
DEBUG:bokeh.server.server:Shutdown: cleaning up
^C

**Comment by karolpiczak** [comment]
```python
File "/home/tmm88/.local/lib/python3.5/site-packages/keras/models.py", line 723, in load_weights
raise ImportError('load_weights requires h5py.')
ImportError: load_weights requires h5py.
```

Seems like there was some problem accessing `h5py`, are you sure it's available?
